<?php

namespace Gaatu\CoreBundle\Repository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{

    public function getJoined($transactionId)
    {
        $qb = $this->createQueryBuilder('transaction');

        return $qb->select('transaction', 'shipment')
            ->join('transaction.shipments', 'shipment')
            ->where('transaction.id = :transaction_id')
            ->setParameters([
                'transaction_id'    =>  $transactionId,
            ])
            ->getQuery()
            ->getOneOrNullResult();
    }
}
